on:
  push:
    branches: ['main']
    tags:
      - 'v*'

# change godot version if needed
env:
  GODOT_VERSION: 4.2

jobs:
  export_game:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Export Game
    steps:
      - name: Run checkout on current branch
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - name: Get Previous tag
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1.3.0'
        with:
          fallback: 0.0.0
          prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get next minor version
        id: semvers
        if: github.ref_name == 'main'
        uses: 'WyriHaximus/github-action-next-semvers@v1'
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Export game
        id: export
        uses: firebelley/godot-export@v5.2.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}-stable_export_templates.tpz
          relative_project_path: "./MeetYourTesterProject/"
          archive_output: true
      
      - name: Create release
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          allowUpdates: true
          # tag: ${{ steps.semvers.outputs.v_minor }}
          tag: ${{ github.ref_name == 'main' && steps.semvers.outputs.v_minor || steps.previoustag.outputs.tag }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*